/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2;

import java.awt.FileDialog;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author luisa
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
     TablaHash t;
     MenuCliente m;
     String opcion;
     NodoLS auxBusqueda;
     
    
    public Cliente() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(0);
        txtKey.setVisible(true); 
        
    }
    public void setDatos(TablaHash t, MenuCliente m){
        this.m=m;
        this.t=t;
    }
    
     public void Accion(String accion){
        opcion=accion;
        switch(accion)
        {
            case "agregar":
                lblTitulo.setText("Registro de clientes");
                btnAccion.setText("Agregar usuario");
                lblKey.setVisible(false);
                txtKey.setVisible(false);
                btnBuscar.setVisible(false);
                btnAccion.setVisible(true);
                btnCarga.setVisible(true);
                
                txtDPI.enable(true);
                txtNombre.enable(true);
                txtApellido.enable(true);
                txtGenero.enable(true);
                txtTelefono.enable(true);
                txtDireccion.enable(true);
                
                
                break;
            case "modificar":
                lblTitulo.setText("Modificar usuario");
                btnAccion.setText("Modificar");
                txtKey.setVisible(true);
                lblKey.setVisible(true);
                btnBuscar.setVisible(true);
                btnAccion.setVisible(true);
                btnCarga.setVisible(false);
                //para que no puedan mostrarse los textos
                txtDPI.enable(false);
                txtNombre.enable(false);
                txtApellido.enable(false);
                txtGenero.enable(false);
                txtTelefono.enable(false);
                txtDireccion.enable(false);
                
                break;
            case "eliminar":
                lblTitulo.setText("Eliminar usuario");
                btnAccion.setText("Eliminar");
                txtKey.setVisible(true);
                lblKey.setVisible(true);
                btnBuscar.setVisible(true);
                btnAccion.setVisible(true);
                btnCarga.setVisible(false);
                //para que no puedan modificarse los textos 
                txtDPI.enable(false);
                txtNombre.enable(false);
                txtApellido.enable(false);
                txtGenero.enable(false);
                txtTelefono.enable(false);
                txtDireccion.enable(false);
                
                break;
            case "mostrar":
                lblTitulo.setText("Mostrar un usuario");
                btnAccion.setText("Mostrar");
                btnBuscar.setVisible(true);
                txtKey.setVisible(true);
                lblKey.setVisible(true);
                btnCarga.setVisible(false);
                btnAccion.setVisible(false);
                //para que no puedan modificarse los textos 
                txtDPI.enable(false);
                txtNombre.enable(false);
                txtApellido.enable(false);
                txtGenero.enable(false);
                txtTelefono.enable(false);
                txtDireccion.enable(false);
                break;
                
                
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDPI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblKey = new javax.swing.JLabel();
        txtKey = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTitulo.setText("Registro de Clientes");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DPI:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Genero:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Telefono:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Direccion:");

        btnAccion.setText("Agregar");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnRegresar.setText("Rregresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        lblKey.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblKey.setText("DPI de usuario a gestionar");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCarga.setText("CargaMasiva");
        btnCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(50, 50, 50)
                                .addComponent(txtTelefono))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(63, 63, 63)
                                .addComponent(txtGenero))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAccion)
                                        .addGap(62, 62, 62)
                                        .addComponent(btnCarga)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRegresar))
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblKey, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtKey)))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)))
                .addGap(52, 244, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKey)
                    .addComponent(txtKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccion)
                    .addComponent(btnRegresar)
                    .addComponent(btnCarga))
                .addGap(139, 139, 139))
        );

        lblTitulo.getAccessibleContext().setAccessibleName("lblTitulo");
        txtDPI.getAccessibleContext().setAccessibleName("DPItxt");
        txtNombre.getAccessibleContext().setAccessibleName("Nombretxt");
        txtApellido.getAccessibleContext().setAccessibleName("Apellido1txt");
        txtGenero.getAccessibleContext().setAccessibleName("Generotxt");
        txtTelefono.getAccessibleContext().setAccessibleName("Telefonotxt");
        txtDireccion.getAccessibleContext().setAccessibleName("Direcciontxt");
        btnAccion.getAccessibleContext().setAccessibleName("btnAgregar");
        btnRegresar.getAccessibleContext().setAccessibleName("btnRegresar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
            // TODO add your handling code here:
           Limpiar();
           m.setHash(t);
           m.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        auxBusqueda=t.Buscar(txtKey.getText());
        
        if(auxBusqueda!=null){
            txtKey.setText("");
            txtDPI.setText(auxBusqueda.DPI);
            txtNombre.setText(auxBusqueda.Nombre);
            txtApellido.setText(auxBusqueda.Apellido);
            txtGenero.setText(auxBusqueda.Genero);
            txtTelefono.setText(auxBusqueda.Telefono);
            txtDireccion.setText(auxBusqueda.Direccion);
            if(opcion.equals("modificar")){
                t.Eliminar(auxBusqueda.DPI);
                txtDPI.enable(true);
                txtNombre.enable(true);
                txtApellido.enable(true);
                txtGenero.enable(true);
                txtTelefono.enable(true);
                txtDireccion.enable(true);
            }
            
        }else{
            txtKey.setText("");
            JOptionPane.showMessageDialog(null, "No se encontro al Cliente con numero de DPI: "+txtKey.getText());
        }
        
            
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        // TODO add your handling code here:
        switch(opcion)
        {
            case "agregar":
                if(txtDPI.getText().equals("")||txtNombre.getText().equals("")|| txtApellido.getText().equals("")|| txtGenero.getText().equals("")||txtTelefono.getText().equals("")||txtDireccion.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "llenar todas las casillas, de lo contrario no es imposible agregar clientes");
                }else{
                    t.Insertar(txtDPI.getText(), txtNombre.getText(), txtApellido.getText(), txtGenero.getText(), txtTelefono.getText(), txtDireccion.getText(),0);
                    
                    Limpiar();
                }
                break;
            case "modificar":
                if(txtDPI.getText().equals("")||txtNombre.getText().equals("")|| txtApellido.getText().equals("")|| txtGenero.getText().equals("")||txtTelefono.getText().equals("")||txtDireccion.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "llenar todas las casillas, de lo contrario no es imposible agregar clientes");
                }else{
                    JOptionPane.showMessageDialog(null, "se Modifico el cliente: "+txtNombre.getText());
                    t.Modificar(txtDPI.getText(), txtNombre.getText(), txtApellido.getText(), txtGenero.getText(), txtTelefono.getText(), txtDireccion.getText());
                    
                    Limpiar();
                }
                break;
            case "eliminar":
                t.Eliminar(txtDPI.getText());
                Limpiar();
                break;
            case "mostrar":
                
                break;
        }
        
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaActionPerformed
     //este string sirve para almacenar la ruta del archivo que selecciones
     String rutatotal="";
     //en este string se guardara todo el archivo de texto
     String registro="";
     //aca te habre un cuadro de dialogo para que busques tu archivo de texto
        FileDialog dialogoArchivo;
        dialogoArchivo = new FileDialog(this, "Lista de Archivos desde Frame",FileDialog.LOAD);
        dialogoArchivo.setVisible(true);
        if(dialogoArchivo.getFile()!=null){ /* Validar que se haya Seleccionado un Archivo*/
           String directorio = dialogoArchivo.getDirectory();
           String nombreArchivo =dialogoArchivo.getFile(); 
            rutatotal= directorio + nombreArchivo;
        }
        //luego que lo seleccionas obtiene la ruta y se la manda 
        //a new file para que lo habra y lo recorra
        try {
            Scanner input = new Scanner(new File("/"+rutatotal));
            while (input.hasNextLine()) {
                String line = input.nextLine();
                //cuando lo va recorriendo lo almacena en el string registro
                registro+=line;
            }
            input.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //despues se crea un arreglo con split del string del archivo completo
        //le pones el delimitador que tiene que tener tu carga masiva al split
        String[] arregloRegistro=registro.split(";");
        for(int x=0;x<arregloRegistro.length;x++){
            //recorres el arreglo ya donde esta separado linea por linea 
            //lo descompones por cada parte sera un atributo para tu insert
            String[] nuevo=arregloRegistro[x].split(",");
            //luego lo inserto en mi estructura
            //va de 0 a 5 porque tengo 6 atributos que guardar
            t.Insertar(nuevo[0], nuevo[1], nuevo[2], nuevo[3], nuevo[4], nuevo[5], 1);
        }
        JOptionPane.showMessageDialog(null, "Carga masiva de clientes completada!");
        
        
    }//GEN-LAST:event_btnCargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

   
    
    public void Limpiar() {
        txtKey.setText("");
        txtDPI.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtGenero.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
    }
    
  
  
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCarga;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblKey;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtKey;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
